name: Kubernetes
title: Kubernetes
url: https://kubernetes.io
description: Production-Grade Container Orchestration
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      fullversion: "v1.8.4"
      version: "v1.8"
      githubbranch: "master"
      docsbranch: "master"
      versions:
      - fullversion: "v1.11.0"
          version: "v1.11"
          githubbranch: "v1.11.0"
          docsbranch: "release-1.11"
          url: https://kubernetes.io/docs/
      - fullversion: "v1.10.0"
          version: "v1.10"
          githubbranch: "v1.10.0"
          docsbranch: "release-1.10"
          url: https://v1-10.docs.kubernetes.io/docs/home/
        - fullversion: "v1.9.0"
          version: "v1.9"
          githubbranch: "v1.9.0"
          docsbranch: "release-1.9"
          url: https://v1-9.docs.kubernetes.io/docs/home/
        - fullversion: "v1.8.4"
          version: "v1.8"
          githubbranch: "v1.8.4"
          docsbranch: "release-1.8"
          url: https://v1-8.docs.kubernetes.io/docs/home/
        - fullversion: "v1.7.6"
          version: "v1.7"
          githubbranch: "v1.7.6"
          docsbranch: "release-1.7"
          url: https://v1-7.docs.kubernetes.io/docs/home/
      deprecated: true
      currentUrl: https://kubernetes.io/docs/home/
      nextUrl: http://kubernetes-io-vnext-staging.netlify.com/
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
# disabled gems
#  - jekyll-redirect-from

include: [_redirects,_headers]

# SEO
logo: /images/favicon.png
twitter:
  username: kubernetesio

# empty array for tabs
emptyArray: []

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - setup
  - tasks
  - tutorials
  - concepts
  - reference
  - samples
  - search
