baseURL = "https://kubernetes.io"
title = "Kubernetes"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

disableKinds = ["taxonomy", "taxonomyTerm"]

ignoreFiles = [ "^OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

contentDir = "content/en"

timeout = 3000

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

# Norwegian ("no") is sometimes but not currently used for testing.
disableLanguages = ["no"]

[blackfriday]
hrefTargetBlank = true
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS", "HEADERS" ]
page = [ "HTML"]
section = [ "HTML"]

# Add a "text/netlify" media type for auto-generating the _headers file
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# _headers file output (uses the template at layouts/index.headers)
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[params]

time_format_blog = "Monday, January 02, 2006"
description = "Production-Grade Container Orchestration"
showedit = true

latest = "v1.15"

fullversion = "v1.11.10"
version = "v1.11"
githubbranch = "v1.11.10"
docsbranch = "release-1.11"
deprecated = true
currentUrl = "https://kubernetes.io/docs/home/"
nextUrl = "https://kubernetes-io-vnext-staging.netlify.com/"
githubWebsiteRepo = "github.com/kubernetes/website"
githubWebsiteRaw = "raw.githubusercontent.com/kubernetes/website"

[[params.versions]]
fullversion = "v1.15.0"
version = "v1.15"
githubbranch = "v1.15.0"
docsbranch = "release-1.15"
url = "https://kubernetes.io"

[params.pushAssets]
css = [
  "callouts",
  "styles",
  "custom-jekyll/tags"
]
js = [
  "custom-jekyll/tags",
  "script"
]

[[params.versions]]
fullversion = "v1.14.3"
version = "v1.14"
githubbranch = "v1.14.3"
docsbranch = "release-1.14"
url = "https://v1-14.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.13.7"
version = "v1.13"
githubbranch = "v1.13.7"
docsbranch = "release-1.13"
url = "https://v1-13.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.12.9"
version = "v1.12"
githubbranch = "v1.12.9"
docsbranch = "release-1.12"
url = "https://v1-12.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.11.10"
version = "v1.11"
githubbranch = "v1.11.10"
docsbranch = "release-1.11"
url = "https://v1-11.docs.kubernetes.io"

# Language definitions.

[languages]
[languages.en]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName ="English"
# Weight used for sorting.
weight = 1

[languages.zh]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName = "中文 Chinese"
weight = 2
contentDir = "content/zh"

[languages.ko]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName = "한국어 Korean"
weight = 3
contentDir = "content/ko"

[languages.no]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName ="Norsk"
weight = 4
contentDir = "content/no"

[languages.no.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]
