snyk-fix-de48698c382ff495fab0d011dca54cb0
FROM nginx:1.25.2
snyk-fix-6e281c5074e7434e9073b359676f5e6f
FROM nginx:1.25.5
=======
FROM nginx:1.26
RUN rm /etc/nginx/conf.d/default.conf
COPY frontend.conf /etc/nginx/conf.d
